export const data_db = {
    cancel: "Cancelar", 
    ok: "Ok", 
    onGps:"Para continuar Ative a localização Do Dispositivo", 
    search: "Procurar", 
    field:"Prencha os Campos", 
    comments: "Comentários", 
    pleaseWait: "Aguarde...", 
    report: "Reportar comentário", 
    map: "Mapa", 
    network:" Sem Coneção Com a Internet Tente Novamente Mas Tarde", 
    erroNetwork:" Erro na Coneção", 
    list: "Lista", 
    send: "Enviar", 
    placeholder:"Digite sua mensagens",
    invalid_zip_code:"Cep Invalido", 
    newMsg: "Nova mensagem", 
    options: "Opções", 
    searchLabel: "O que você procura?", 
    empty: "Nenhum item encontrado", 
    more: "Mais", 
    back: "Voltar", 
    access_your_location:"Liza Moda Quer Acessar Sua Localização !", 
    empty_field :"Campo Vazio", 
    refreshing: "Atualizando", 
    pullToRefresh: "Puxe para atualizar" 
 };
